### ISSUE TITLE
list_cos_objects needs to page through listing results

### ISSUE THREAD

**Issue by torsstei** [IBM-Cloud/sql-query-clients#49]
Current implementation of list_cos_objects here https://test.cloud.ibm.com/docs/services/sql-query?topic=sql-query-overview#database-locations does only do single GET objects calls to COS, which only returns 1000 objects max. It should be improved to use e.g. ibm_boto3 client like in get_cos_summary to page through all results and construct a combined data frame to return when more than 1000 object match the input prefix.

**Comment by shawnzhu** [comment]
## Summary

1. It uses low level protocol to talk to COS service in the current `list_cos_objects()` via `requests` which will need more logic to implement feature like auto-pagination. https://github.com/IBM-Cloud/sql-query-clients/blob/2421f0634b959ea2a8b6a67de02c0747b95873d6/Python/ibmcloudsql/SQLQuery.py#L546
1. there are code uses service model API (e.g., `ibm_boto3.client`) to talk to COS. such API supports pagination feature well, but still requires awareness of low-level API like `paginator`.
1. it supports high level API like resource model in IBM COS SDK which handles such logic via chained api like:

```Python
cos = ibm_boto3.resource("s3",
    ibm_api_key_id=COS_API_KEY_ID,
#    ibm_service_instance_id=COS_RESOURCE_CRN,
    ibm_auth_endpoint=COS_AUTH_ENDPOINT,
    config=Config(signature_version="oauth"),
    endpoint_url=COS_ENDPOINT
)

objs = cos.Bucket('waas-analytics').objects.filter(Prefix='kzhu/slack-experiment/')

print(list(objs))
```

I will try to see if 3) path is possible since the constructor of resource model requires COS CRN which is unavailable from this SDK.

**Comment by torsstei** [comment]
@shawnzhu I've now refactored the SDK to use a common method for boto3 cos client. Also enhanced list_cos_objects to return size of objects again.

**Comment by shawnzhu** [comment]
Fixed by https://github.com/IBM-Cloud/sql-query-clients/commit/d8ac5f2c711b66bbd434851c3813c5899231ac35
